### ISSUE TITLE
negative string size (or size too big)

### ISSUE THREAD

**Issue by modeandclay** [ankane/blingfire#3]
```
require 'blingfire'

sentence = "How now, brown cow?"

model = BlingFire.load_model("gpt2.bin")
ids = model.text_to_ids(sentence)

model.ids_to_text(ids)
```

I expect `model.ids_to_text(ids) == sentence`.

However, `model.ids_to_text(ids)` errors with the message:

```
.../ruby-3.1.2/gems/blingfire-0.2.0/lib/blingfire.rb:122:in `to_str': negative string size (or size too big) (ArgumentError)
.../ruby-3.1.2/gems/blingfire-0.2.0/lib/blingfire.rb:122:in `ids_to_text'
.../ruby-3.1.2/gems/blingfire-0.2.0/lib/blingfire/model.rb:66:in `ids_to_text'
```

**Comment by modeandclay** [comment]
I clearly need coffee. `gpt2.i2w` is needed to convert ids back to words.

```
require 'blingfire'

sentence = "How now, brown cow?"

model = BlingFire.load_model("gpt2.bin")
ids = model.text_to_ids(sentence)

model = BlingFire.load_model("gpt2.i2w")
puts model.ids_to_text(ids)
```

**Comment by ankane** [comment]
Hi @codeandclay, thanks for reporting. Fixed the confusing error in the commit above, but unfortunately don't see a way to detect the wrong type of model.
